linter:
  rules:
    avoid_print: false
    file_names: false
    curly_braces_in_flow_control_structures: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    unnecessary_new: false
    unnecessary_this: false
    prefer_conditional_assignment: false
    avoid_function_literals_in_foreach_calls: false
    use_key_in_widget_constructors: false